server:
  port: 8082
  servlet:
    context-path: /notification
spring:
  application:
    name: notification-service
  data:
    mongodb:
      uri: 
app:
  services:
    mail: 
      api: your_mail_service_api
      key: your_mail_service_key
