server:
  port: 8888

app:
  api-prefix: /api/v1
  prefix-length: 2

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: identity_service
          uri: http://localhost
          predicates:
          - Path=${app.api-prefix}/identity/**
          filters:
          - StripPrefix=${app.prefix-length}
        - id: profile_service
          uri: http://localhost
          predicates:
            - Path=${app.api-prefix}/profile/**
          filters:
          - StripPrefix=${app.prefix-length}
        - id: notification_service
          uri: http://localhost
          predicates:
            - Path=${app.api-prefix}/notification/**
          filters:
            - StripPrefix=${app.prefix-length}
